package apps.controller;

//The enum of all entities of the game (Items, mobs)
public enum EntitiesEnum {
    HEAL_POTION,
    POISON_POTION,
    DEFENSE_POTION,
    ATTACK_POTION,
    MAGIC_POTION,
    SPEED_POTION,
    HOLY_GRENADE,
    KEY,
    FOOD,
    WALL,
    DOOR,
    EXIT,
    TREASURE,
    DEATH,
    DAEMON,
    GHOST,
    GRUNT,
    LOBBER,
    SPAWNER_GRUNT1,
    SPAWNER_GRUNT2,
    SPAWNER_GRUNT3,
    SPAWNER_DAEMON1,
    SPAWNER_DAEMON2,
    SPAWNER_DAEMON3,
    SPAWNER_LOBBER1,
    SPAWNER_LOBBER2,
    SPAWNER_LOBBER3,
    SPAWNER_GHOST1,
    SPAWNER_GHOST2,
    SPAWNER_GHOST3,
    SPAWN_HERO,
    DELETE
}
